name: Teste unitário e Lint

on: push

jobs:
  Testando_codigo:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api  # <- se você usa uma pasta "api", ajuste aqui

    steps:
      - name: Obter código do repositório
        uses: actions/checkout@v3

      - name: Instala Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instala dependências
        run: npm ci

      - name: Roda Lint
        run: npm run lint

      - name: Roda Testes
        run: npm test

      - name: Gera relatório de testes
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Jest Tests
          path: reports/jest-junit.xml   # <- caminho correto do arquivo XML
          reporter: jest-junit
