name: Testes unitários com relatório

on:
  push:
    branches: [main, dev, stable, prod]

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        default: dev
        options:
          - dev
          - prod
          - stage

jobs:
  test:
    name: Execução dos Testes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Obter código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar ESLint (opcional)
        run: npm run lint
        continue-on-error: true

      - name: Rodar testes
        run: npm test

      - name: Verificar se relatório foi gerado
        run: find . -name "jest-junit.xml"

      - name: Upload do relatório como artefato (opcional)
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-jest
          path: reports/jest-junit.xml

  jest-report:
    name: JEST tests
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Baixar relatório de testes
        uses: actions/download-artifact@v3
        with:
          name: relatorio-jest

      - name: Gerar visualização dos testes
        uses: dorny/test-reporter@v1
        with:
          name: JEST tests
          path: relatorio-jest/jest-junit.xml
          reporter: jest-junit
          list-suites: all
          list-tests: all
          fail-on-empty: true
          fail-on-error: true